logging:
  file:
    path: ./logs

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: webdiet-authorization-service
  messages:
    basename: lang/messages
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/webdiet-auth
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
server:
  port: 8888
